apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ujpix5xvl-nodejs 
  janus-idp.io/tekton: ujpix5xvl-nodejs
  backstage.io/kubernetes-id: ujpix5xvl-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ujpix5xvl-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml