apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ujpix5xvl-nodejs
  janus-idp.io/tekton: ujpix5xvl-nodejs
  backstage.io/kubernetes-id: ujpix5xvl-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ujpix5xvl-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
